建置環境

要先下載Numpy的配件

pip install Numpy
C:\Users\Your Name>pip install numpy

vscode 的 ipynd Numpy 下載則是

!pip install Numpy

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


首先來練習建立一個Numpy的陣列

In [2]:
import numpy as np # type: ignore

In [3]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


什麼是Numpy?

Numpy具有在線性代數、傅立葉變換和矩陣領域中工作的功能。

為什麼要使用 NumPy？

其中一個原因是傳統的Array執行太慢
NumPy 中的陣列物件被稱為ndarray，它提供了許多支援函數，使得使用變得 ndarray非常容易。

練習建立0維、1維、2維、3維數組

In [4]:
zero_arr = np.array(42) # 0維
one_arr = np.array([1, 2, 3, 4, 5]) # 1維
two_arr = np.array([[1, 2, 3], [4, 5, 6]]) # 2維
three_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # 3維

print(f'我是零維 : \n {zero_arr}')
print(f'我是一維 : \n {one_arr}')
print(f'我是二維 : \n {two_arr}')
print(f'我是三維 : \n {three_arr}')

我是零維 : 
 42
我是一維 : 
 [1 2 3 4 5]
我是二維 : 
 [[1 2 3]
 [4 5 6]]
我是三維 : 
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


練習查詢維度數
使用ndim

In [5]:
print(zero_arr.ndim)
print(one_arr.ndim)
print(two_arr.ndim)
print(three_arr.ndim)

0
1
2
3


練習建立一個高維度數組

In [6]:
high_arr = np.array([1, 2, 3, 4], ndmin=5)
print(high_arr)

[[[[[1 2 3 4]]]]]


練習抓取對應位置

In [7]:
arr = np.array([1, 2, 3, 4])
three_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr[0])
# 第一個元素的索引值是 0
print(arr[1] , end='\n\n')
# 第二個元素的索引值是 1

print(three_arr[0][0][0])
# 三維陣列的索引值是 [x][y][z]，x 代表第幾個陣列，y 代表第幾個元素，z 代表第幾個值
print(three_arr[1][0][1])
# 依此類推


1
2

1
2


練習切取索引 

In [8]:
arr = np.array([1, 2, 3, 4 , 5, 6, 7, 8, 9, 10])

print(arr[1:5])
# 1 到索引 5 的元素
print(arr[4:])
# 索引 4 之後的元素
print(arr[:4])
# 索引 4 之前的元素
print(arr[-3:-1])
# 從後面數來的第三個元素到最後一個元素
print(arr[1:5:2])
# 從索引 1 到索引 5，每個元素取一次
print(arr[::2])
# 從頭到尾，每個元素取一次
print(arr[1::2])
# 從索引 1 到最後，每個元素取一次
print(arr[-1::-1])
# 從最後一個元素到頭，每個元素取一次

[2 3 4 5]
[ 5  6  7  8  9 10]
[1 2 3 4]
[8 9]
[2 4]
[1 3 5 7 9]
[ 2  4  6  8 10]
[10  9  8  7  6  5  4  3  2  1]


>print(arr[:5:]) 0有包含道 5則沒有 因此只會顯示0~4

python 中的資料類型<br>

strings- 用於表示文字數據，文字在引號下給出。例如“ABCD” <br>
integer- 用來表示整數。例如 -1、-2、-3<br>
float- 用來表示實數。例如 1.2、42.42<br>
boolean- 用來表示真或假。<br>
complex- 用來表示複數。例如 1.0 + 2.0j、1.5 + 2.5j<br>

NumPy 中的資料類型<br>

i- 整數<br>
b- 布林值<br>
u- 無符號整數<br>
f- 漂浮<br>
c- 複雜浮點數<br>
m- 時間增量<br>
M- 日期時間<br>
O- 目的<br>
S- 細繩<br>
U- unicode字串<br>
V- 修復了其他類型（void）的記憶體區塊<br>

Numpy的dtype可以去查詢陣列內的資料類型

In [9]:
int_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
str_arr = np.array(['apple', 'banana', 'cherry'])
float_arr = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
bool_arr = np.array([True, False, True])

print(arr.dtype)
print(str_arr.dtype)
print(float_arr.dtype)
print(bool_arr.dtype)

int64
<U6
float64
bool


在 Python 中，當傳遞給函數的參數類型意外/不正確時，會引發 ValueError。

In [10]:
# arr = np.array(['a', '2', '3'], dtype='i')

# 因為 'a' 無法轉換成整數，所以會報錯

練習轉換現有數組的資料類型

In [11]:
arr = np.array([1.1, 2.1, 3.1])
# 原本是float的陣列

arr = arr.astype('i')
# i是整數的意思

print(arr)
print(arr.dtype)

[1 2 3]
int32


>對於boolen -1和1是True 0是False

複製和查看之間的區別

副本擁有數據，對副本所做的任何更改都不會影響原始數組，對原始數組所做的任何更改也不會影響副本。

視圖不擁有數據，對視圖所做的任何變更都會影響原始數組，並且對原始數組所做的任何更改都會影響視圖。

In [12]:
arr = np.array([1, 0, 3])

copy_arr = arr.copy()

copy_arr[0] = 42

print(arr)
print(copy_arr)

[1 0 3]
[42  0  3]


In [13]:
view_arr = arr.view()

view_arr[0] = 42

print(arr)
print(view_arr)

[42  0  3]
[42  0  3]


檢查數組是否擁有其數據 可以用base

In [14]:
print(copy_arr.base)
print(view_arr.base)

None
[42  0  3]


數組的形狀是每個維度中元素的數量。

NumPy 數組有一個名為的屬性shape，它傳回一個元組，其中每個索引都有相應元素的數量。

In [15]:
arr = np.array([[1 , 2 , 3] , [4 , 5 , 6]])

five_arr = np.array([1 , 2 , 3 , 4] , ndmin=5)

print(arr.shape)
print(five_arr.shape)

(2, 3)
(1, 1, 1, 1, 4)


>[[[[1,2,3,4,5]]]]<br>
這樣會出現(1,1,1,1,5)<br>
也就是第一維度有1個元素 []<br>
依此類推<br>
第二維度有1個元素 []<br>
第三維度有1個元素 []<br>
第四維度有1個元素 []<br>
第五維度有5個元素 1,2,3,4,5<br>

重塑數組 透過reshape 

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10 , 11, 12])

new_arr = arr.reshape(4, 3)
# 把原本的陣列改成 4 個陣列，每個陣列有 3 個元素

print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
new_arr = arr.reshape(2, 3, 2)
# 把原本的陣列改成 2 個陣列，每個陣列有 3 個元素，每個元素有 2 個值

print(new_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


>在重塑數組的時候不可以隨意重組 ex:8個值無法分為(3,2)

In [18]:
print(arr.reshape(2, 3, 2).base)
# 來看是view還是copy

[ 1  2  3  4  5  6  7  8  9 10 11 12]


如果不知道也可以用未知維度(-1)

In [19]:
arr = np.array([1, 2, 3 , 4, 5, 6, 7, 8, 9, 10, 11, 12])

new_arr = arr.reshape(2, 3, -1)

print(new_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


數組迭代

當我們處理 numpy 中的多維數組時，我們可以使用 forpython 的基本循環來完成此操作。

In [20]:
arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


In [21]:
two_arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in two_arr:
    print(x)

[1 2 3]
[4 5 6]


In [22]:
for x in two_arr:
    for y in x:
        print(y)

1
2
3
4
5
6


使用 nditer() 迭代數組

nditer()是一個輔助功能，可以從非常基礎的到非常高級的迭代使用 取代多維for的方式

In [23]:
height_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

for x in np.nditer(height_arr):
    print(x)

1
2
3
4
5
6
1
2
3
4
5
6


迭代具有不同資料類型的數組

我們可以使用op_dtypes參數並傳遞預期的資料類型來在迭代時改變元素的資料類型。

In [24]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


使用不同步長進行迭代

我們可以使用過濾，然後進行迭代。

In [25]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


使用 ndenumerate() 進行列舉迭代

枚舉的意思是逐一提及事物的序號。

有時我們在迭代時需要元素的相應索引，該ndenumerate()方法可用於這些用例。

In [26]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [27]:
two_arr = np.array([[1, 2, 3], [4, 5, 6]])

for idx , x in np.ndenumerate(two_arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


連接 NumPy 數組

我們將想要加入的陣列序列 concatenate()與軸一起傳遞給函數。如果沒有明確傳遞軸(axis)，則將其視為 0。

In [28]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

new_arr = np.concatenate((arr1, arr2))

print(new_arr)

[1 2 3 4 5 6]


In [29]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

new_arr = np.concatenate((arr1, arr2), axis=1)

print(new_arr)

[[1 2 5 6]
 [3 4 7 8]]


使用堆疊函數連接數組

將想要加入的陣列序列 stack()與軸一起傳遞給方法。如果沒有明確傳遞軸(axis)，則將其視為 0。

In [30]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

new_arr = np.stack((arr1, arr2), axis=1)

print(new_arr)

[[1 4]
 [2 5]
 [3 6]]


沿行堆疊

NumPy 提供了一個輔助函數：hstack() 沿著行堆疊。

In [31]:
new_arr = np.hstack((arr1, arr2))

print(new_arr)

[1 2 3 4 5 6]


沿列堆疊

NumPy 提供了一個輔助函數：vstack()  沿著列堆疊。

In [32]:
new_arr = np.vstack((arr1, arr2))

print(new_arr)

[[1 2 3]
 [4 5 6]]


沿高度（深度）堆疊

NumPy 提供了一個輔助函數：dstack() 沿著高度堆疊，與深度相同。

In [33]:
new_arr = np.dstack((arr1, arr2))

print(new_arr)

[[[1 4]
  [2 5]
  [3 6]]]


拆分 NumPy 數組

可以用array_split()來分割數組，我們將想要分割的數組和分割的次數傳遞給它。

In [34]:
arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = np.array_split(arr, 3)

print(new_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


>如果陣列的元素少於所需元素，則它將從末尾進行相應調整。

In [35]:
arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = np.array_split(arr, 4)

print(new_arr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


拆分成數組

此方法的傳回值array_split()是一個包含每個分割的陣列。

如果將一個陣列拆分為 3 個數組，則可以像存取任何數組元素一樣從結果中存取它們：

In [36]:
print(new_arr[0])
print(new_arr[1])
print(new_arr[2])

[1 2]
[3 4]
[5]


In [37]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

new_arr = np.array_split(arr, 3)

print(new_arr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [38]:
new_arr = np.array_split(arr, 3, axis=1)

print(new_arr)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int64)]


使用此hsplit()方法將二維數組沿行拆分為三個二維數組。

In [39]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

new_arr = np.hsplit(arr, 3)

print(new_arr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


>vstack()和 的 類似替代品dstack()有 vsplit()和 dsplit()。

搜尋數組

要搜尋數組，請使用where()方法。

In [40]:
arr = np.array([1 ,2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


搜尋已排序

有一種方法searchsorted()可以在數組中執行二進制搜索，並返回插入指定值以維持搜索順序的索引。

In [41]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


從右側搜尋

In [42]:
x = np.searchsorted(arr, 7, side='right')

print(x)

2


插入多個值

In [43]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


數組排序

NumPy ndarray 物件有一個名為的函數sort()，它將對指定的陣列進行排序。

In [44]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


字串按字母順序對數組進行排序：

In [45]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


對布林排序

In [46]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


對二維排序

In [47]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


過濾數組

在 NumPy 中，您可以使用布林索引清單過濾陣列。

In [48]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

new_arr = arr[x]

print(new_arr)

[41 43]


建立過濾器數組

In [49]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


直接從數組建立過濾器

In [50]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
